// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNsrMRdhej0GY2T7nHMerRh98qkK4G6rM',
    appId: '1:662414948226:web:2ddfb44e8c767b0c06419b',
    messagingSenderId: '662414948226',
    projectId: 'sheff-andrew-e1613',
    authDomain: 'sheff-andrew-e1613.firebaseapp.com',
    storageBucket: 'sheff-andrew-e1613.appspot.com',
    measurementId: 'G-JW6NRP39ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkhxrsknDpl8dApMpsgt8K7VCjh_MG2I',
    appId: '1:662414948226:android:6646e7d9e03ab68f06419b',
    messagingSenderId: '662414948226',
    projectId: 'sheff-andrew-e1613',
    storageBucket: 'sheff-andrew-e1613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6YR929-HTm_skztHEsS3gwoIb6RwGbg',
    appId: '1:662414948226:ios:18921e89429a03b506419b',
    messagingSenderId: '662414948226',
    projectId: 'sheff-andrew-e1613',
    storageBucket: 'sheff-andrew-e1613.appspot.com',
    iosBundleId: 'com.example.sheffAndrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6YR929-HTm_skztHEsS3gwoIb6RwGbg',
    appId: '1:662414948226:ios:18921e89429a03b506419b',
    messagingSenderId: '662414948226',
    projectId: 'sheff-andrew-e1613',
    storageBucket: 'sheff-andrew-e1613.appspot.com',
    iosBundleId: 'com.example.sheffAndrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNsrMRdhej0GY2T7nHMerRh98qkK4G6rM',
    appId: '1:662414948226:web:f2690f18484d1c2a06419b',
    messagingSenderId: '662414948226',
    projectId: 'sheff-andrew-e1613',
    authDomain: 'sheff-andrew-e1613.firebaseapp.com',
    storageBucket: 'sheff-andrew-e1613.appspot.com',
    measurementId: 'G-EJQG1KXS26',
  );
}
